### PR TITLE
datetime added to user model

### PR DESCRIPTION
**Pull request by mariiamakura**
hey, I added registration_date into user model + to debug_routes to check it at "/get-users"

### CODE REVIEW

**Comment by dantol29** [comment]
Nice, did you apply migrations locally and on on Digital Ocean?

**Comment by mariiamakura** [comment]
I tested everything locally with dockerized backend and database, should work :)
I didn't dare to push it to the production in the cloud before pull request is reviewed

**Comment by dantol29** [comment]
Cool, I gonna approve. Can you perform migration on the cloud too?

**Comment by mariiamakura** [comment]
Thanks! Sure, I can

**Pull request merged**
